[tool.poetry]
name = "cryptic"
version = "1.0.1"
description = ""
authors = ["Camille Scott <camille.scott.w@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
cryptic = "cryptic.__main__:main" 

[tool.poetry.dependencies]
python = "^3.12"
openai = "^2.36.0"
rich = "^13.9.3"
python-frontmatter = "^1.1.0"
ponderosa = {extras = ["rich"], version = "^0.6.0"}
pillow = "^11.0.0"
pyyaml = "^6.0"
asyncinotify = "^4.0"
python-dotenv = "^1.2.2"


[tool.poetry.group.dev.dependencies]
ipython = "^8.28.0"


[tool.poetry.group.tests.dependencies]
pytest = "^8.3.3"
tox = "^4.23.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.requires-plugins]
poetry-bumpversion = ">=0.3.3"

[tool.poetry_bumpversion.file."cryptic/__init__.py"]
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"
